#ifndef __CalculateDialog__
#define __CalculateDialog__

/**
@file
Subclass of TCalculateDialog, which is generated by wxFormBuilder.
*/

#include "GUI.h"

/** Implementing TCalculateDialog */
class CalculateDialog : public TCalculateDialog
{
public:
	/** Constructor */
	CalculateDialog( wxWindow* parent );
};

#endif // __CalculateDialog__
