#ifndef __ClockAdjust__
#define __ClockAdjust__

#include "stdafx.h"
#include "TimeControl.h"

/**
@file
Subclass of TClockAdjust, which is generated by wxFormBuilder.
*/

#include "GUI.h"

/** Implementing TClockAdjust */
class ClockAdjustDialog : public TClockAdjustDialog
{
protected:
	// Handlers for TClockAdjust events.
	void doOK( wxCommandEvent& event );
        void doCancel( wxCommandEvent& event );
        void doInit( wxInitDialogEvent& event );
	
public:
	/** Constructor */
	ClockAdjustDialog( wxWindow* parent );
        void setTimeControl(TimeControl tc);
        TimeControl getTimeControl(void);

private:
        TimeControl m_tc;
};

#endif // __ClockAdjust__
