/* Autogenerated by hxtools bin2c */
#ifndef IMAGES_HPP
#define IMAGES_HPP 1

class wxBitmap;

extern "C" void bin2c_init_IMAGES_HPP(void);
extern wxBitmap *bin2c_analyze_bmp;
extern wxBitmap *bin2c_back_bmp;
extern wxBitmap *bin2c_blackstone_bmp;
extern wxBitmap *bin2c_delete_bmp;
extern wxBitmap *bin2c_execute_bmp;
extern wxBitmap *bin2c_fileopen_bmp;
extern wxBitmap *bin2c_filesaveas_bmp;
extern wxBitmap *bin2c_filesave_bmp;
extern wxBitmap *bin2c_find_bmp;
extern wxBitmap *bin2c_forward_bmp;
extern wxBitmap *bin2c_goparent3_bmp;
extern wxBitmap *bin2c_leela_ico;
extern wxBitmap *bin2c_minus_bmp;
extern wxBitmap *bin2c_new_bmp;
extern wxBitmap *bin2c_new_dir_bmp;
extern wxBitmap *bin2c_newrated_bmp;
extern wxBitmap *bin2c_plus_bmp;
extern wxBitmap *bin2c_quit_bmp;
extern wxBitmap *bin2c_resign_bmp;
extern wxBitmap *bin2c_redo_bmp;
extern wxBitmap *bin2c_sethome_bmp;
extern wxBitmap *bin2c_undo_bmp;
extern wxBitmap *bin2c_whitestone_bmp;
extern wxBitmap *bin2c_wood_bmp;
extern wxBitmap *bin2c_leela_mock_ico;


#endif /* IMAGES_HPP */
