#ifndef __NagDialog__
#define __NagDialog__

#include "stdafx.h"

/**
@file
Subclass of TNagDialog, which is generated by wxFormBuilder.
*/

#include "GUI.h"

/** Implementing TNagDialog */
class NagDialog : public TNagDialog
{
public:
	/** Constructor */
	NagDialog( wxWindow* parent );
};

#endif // __NagDialog__
