#ifndef __NewGameDialog__
#define __NewGameDialog__

#include "stdafx.h"

/**
@file
Subclass of TNewGameDialog, which is generated by wxFormBuilder.
*/

#include "GUI.h"

/** Implementing TNewGameDialog */
class NewGameDialog : public TNewGameDialog
{
public:
	/** Constructor */
	NewGameDialog( wxWindow* parent );
};

#endif // __NewGameDialog__
