#ifndef __NewGameDialog__
#define __NewGameDialog__

#include "stdafx.h"

/**
@file
Subclass of TNewGameDialog, which is generated by wxFormBuilder.
*/

#include "GUI.h"

/** Implementing TNewGameDialog */
class NewGameDialog : public TNewGameDialog
{
protected:
    virtual void doKomiUpdate( wxSpinEvent& event );
    virtual void doCancel( wxCommandEvent& event );
    virtual void doOK( wxCommandEvent& event );
public:
    /** Constructor */
    NewGameDialog( wxWindow* parent );                
    
    /* getters/setters */
    float getKomi();
    int getHandicap();
    int getBoardsize();
    int getSimulations();
    int getPlayerColor();
};

#endif // __NewGameDialog__
