#ifndef __RatedSizeDialog__
#define __RatedSizeDialog__

/**
@file
Subclass of TRatedSizeDialog, which is generated by wxFormBuilder.
*/

#include "GUI.h"

/** Implementing TRatedSizeDialog */
class RatedSizeDialog : public TRatedSizeDialog
{
protected:
	// Handlers for TRatedSizeDialog events.
	void doSize9( wxCommandEvent& event );
	void doSize19( wxCommandEvent& event );
	int m_sizeSelected;

public:
	/** Constructor */
	RatedSizeDialog( wxWindow* parent );
        int getSizeSelected();
        
};

#endif // __RatedSizeDialog__
