#ifndef __ScoreDialog__
#define __ScoreDialog__

/**
@file
Subclass of TScoreDialog, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing TScoreDialog */
class ScoreDialog : public TScoreDialog
{
	protected:
		// Handlers for TScoreDialog events.
		void doAccept( wxCommandEvent& event );
		void doDispute( wxCommandEvent& event );
                bool mAccepts{false};
	public:
		/** Constructor */
		ScoreDialog( wxWindow* parent, wxString message,
                             wxString confidence );
                bool Accepted() { return mAccepts; };
	//// end generated class members

};

#endif // __ScoreDialog__
