#ifndef __ScoreHistogram__
#define __ScoreHistogram__

#include "stdafx.h"

/**
@file
Subclass of TScoreHistogram, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing TScoreHistogram */
class ScoreHistogram : public TScoreHistogram
{
	public:
		/** Constructor */
		ScoreHistogram( wxWindow* parent );
                void ClearHistogram();
	//// end generated class members
        private:
            void doNewScore(wxCommandEvent& event);
            void doPaint(wxPaintEvent& event);

            static std::vector<std::tuple<int, float, float, float>> m_scores;
            friend class TScorePanel;

};

#endif // __ScoreHistogram__
