#ifndef __SettingsDialog__
#define __SettingsDialog__

/**
@file
Subclass of TSettingsDialog, which is generated by wxFormBuilder.
*/

#include "stdafx.h"
#include "GUI.h"

//// end generated include

/** Implementing TSettingsDialog */
class SettingsDialog : public TSettingsDialog
{
    protected:
        virtual void doInit( wxInitDialogEvent& event );
        virtual void doCancel( wxCommandEvent& event );
        virtual void doOK( wxCommandEvent& event );

    public:
	/** Constructor */
	SettingsDialog( wxWindow* parent );
	//// end generated class members
};

#endif // __SettingsDialog__
